final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('readings.urls')),

]

readings/urls.py
from django.urls import path
from .views import LoginView, DetailUser, LogoutView, RegisterView, create_lectura, update_lectura, delete_lectura

app_name = 'consumer'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('detail_user/<int:pk>/', DetailUser.as_view(), name='detail_user'),
    path('create_lectura/', create_lectura, name='create_lectura'),
    path('update_lectura/<int:pk>', update_lectura, name='update_lectura'),
    path('delete_lectura/<int:pk>', delete_lectura, name='delete_lectura'),
]

readings/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass

class Lectura(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title_book = models.CharField(max_length=70)
    init_date = models.DateField()
    state = models.BooleanField(default=True)

    def __str__(self):
        return self.title_book

readings/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


from .models import Lectura, User
class LoginForm(AuthenticationForm):
    pass

class SigninForm(UserCreationForm):
    email = forms.EmailField(label='email')
    first_name = forms.CharField(label='first name')
    last_name = forms.CharField(label='last name')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')



class CreateLectura(forms.ModelForm):
    title_book = forms.CharField(label='Title',
                            max_length=70,
                            widget=forms.TextInput(
                                attrs={'class': 'form-control',
                                       'placeholder': 'Enter your title'}))
    state = forms.BooleanField(label='Complete',
                                    required=True,
                                    widget=forms.CheckboxInput(
                                        attrs={'class': 'form-check-input',
                                               'type': 'checkbox',
                                               'role': 'switch',
                                               'id': 'flexSwitchCheckDefault'}))
    init_date= forms.DateField(label='Init Date',
                               widget=forms.DateInput(
                                   attrs={'class': 'form-control input-element',
                                          'placeholder': 'YYYY-MM-DD'}))

    class Meta:
        model = Lectura
        fields = ('title_book', 'state', 'date')

readings/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, RedirectView, FormView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from .models import Lectura, User
from .forms import CreateLectura, LoginForm, SigninForm
from django.urls import reverse_lazy
# Create your views here.

class LoginView(FormView):
    pass

class LoginView(FormView):
    form_class = LoginForm
    template_name = 'readings/login.html'
    success_url = reverse_lazy('readings:detail_user')

    def form_valid(self, form):
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None and user.is_active:
                login(self.request, user)
                return super(LoginView, self).form_valid(form)
            else:
                return self.form_invalid(form)

    def get_success_url(self):
        return reverse_lazy('readings:detail_user', kwargs={'pk': self.request.user.pk})

class DetailUser(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'readings/detail_user.html'

    def get_context_data(self, **kwargs):
        context = super(DetailUser, self).get_context_data(**kwargs)
        user = User.objects.get(pk=self.request.user.pk)
        lecturas = Lectura.objects.filter(user=user)
        context['user'] = user
        context['lecturas'] = lecturas
        return context

class LogoutView(LoginRequiredMixin, RedirectView):
    url = reverse_lazy('consumer:login')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)



class RegisterView(CreateView):
    form_class = SigninForm
    model = User
    template_name = 'readings/register.html'
    success_url = reverse_lazy('readings:login')

    def form_valid(self, form):
        form.save()
        return super(RegisterView, self).form_valid(form)


@login_required
def create_lectura(request):
    if request.method == 'POST':
        form = CreateLectura(request.POST)
        if form.is_valid():
            lectura = form.save(commit=False)
            lectura.user = request.user
            lectura.save()
            return redirect(reverse_lazy('lectura:detail_user', kwargs={'pk': request.user.pk}))
    else:
        form = CreateLectura()
    return render(request, 'lectura/create_lectura.html', {'form': form})


@login_required
def update_lectura(request, pk):
    lectura = Lectura.objects.get(pk=pk)
    if request.method == 'POST':
        form = CreateLectura(request.POST, instance=lectura)
        if form.is_valid():
            lectura = form.save(commit=False)
            lectura.user = request.user
            lectura.save()
            return redirect(reverse_lazy('lectura:detail_user', kwargs={'pk': request.user.pk}))
    else:
        form = CreateLectura(instance=lectura)
    return render(request, 'consumer/create_lectura.html', {'form': form})

@login_required
def delete_lectura(request, pk):
    lectura = Lectura.objects.get(pk=pk)
    lectura= lectura.delete()
    return redirect(reverse_lazy('lectura:detail_user', kwargs={'pk': request.user.pk}))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Django Advanced{% endblock %}</title>
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
</head>
<body>
    {% block content %}
    {% endblock %}
    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cleave.js/1.6.0/cleave.min.js"></script>
    {% block js %}{% endblock %}
</body>
</html>

templates/lectura/create_lectura.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <h1 class="text-center mt-4">Add Task</h1>
    <form action="" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-success mt-2 button">Create</button>
</form>
</div>

{% endblock %}
{% block js %}
<script>

let cleave = new Cleave('.input-element', {
    date: true,
    delimiter: '-',
    datePattern: ['Y', 'm', 'd']
});


</script>
{% endblock %}

templates/lectura/detail_user.html
{% extends 'base.html' %}
{% block title %} {{user.username|capfirst}} {% endblock %} 
{% load static %}
{% block content%}
{% include 'consumer/navbar.html' %}
<div class="container">
    <h1 class="text-center mt-3 mb-5">Welcome {{user.username}}</h1>
</div>
{% if tasks %}
<div class="container">
  <table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Complete?</th>
      <th scope="col">Date</th>
      <th scope="col">Update</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for task in tasks %}
        <tr>
            <th scope="row">{{lectura.id}}</th>
            <td>{{lectura.title}}</td>
            {% if lectura.state %}
              <td><span class="badge bg-success">Yes</span></td>
            {% else %}
              <td><span class="badge bg-danger">No</span></td>
            {% endif %}
            <td>@{{task.date}}</td>
            <td><a href="{% url 'lectura:update_lectura' lectura.id %}" class="btn btn-info">Update</a></td>
            <td><a href="{% url 'lectura:delete_lectura' lectura.id %}" class="btn btn-danger">Delete</a></td>
        </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% else %}
<h3 class="text-center mb-5">No hay tareas</h3>
{% endif %}
{% endblock %}

templates/lectura/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5 mb-4 p-5 rounded-3 col-12 col-sm-10 col-md-8 col-lg-6 col-xl-6 col-xxl-6" id="form-login">
        <h1 class="text-center">Welcome new user</h1>
        {% load crispy_forms_tags %}
        <form action="{% url 'consumer:login' %}" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-success w-25 mt-4">Login</button>
                <a href="{% url 'consumer:register' %}"class="btn btn-primary w-25 mt-4">Register</a>
            </div>
        </form>
    </div>
{% endblock %}